services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"